# Generated by Django 5.1.1 on 2024-12-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='media/usuarios'),
        ),
    ]
