# Generated by Django 5.1.4 on 2024-12-11 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_descricao_servicos_profissional_biografia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='especialidades',
        ),
        migrations.AddField(
            model_name='profissional',
            name='especialidade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.especialidade'),
        ),
    ]
