# Generated by Django 5.1.4 on 2024-12-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_profissional_especialidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
