# Generated by Django 5.1.4 on 2024-12-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_endereco_estado_cidade_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
